// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, real, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const products = sqliteTable("products", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text().notNull(),
	category: text().notNull(),
	price: real().notNull(),
	stock: integer().default(0),
	imageUrl: text("image_url"),
	description: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_products_category").on(table.category),
]);

export const orders = sqliteTable("orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	total: real().notNull(),
	status: text().default("pending"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_orders_user_id").on(table.userId),
]);

export const orderItems = sqliteTable("order_items", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderId: integer("order_id").notNull().references(() => orders.id),
	productId: integer("product_id").notNull().references(() => products.id),
	quantity: integer().notNull(),
	price: real().notNull(),
},
(table) => [
	index("idx_order_items_order_id").on(table.orderId),
]);


export const banners = sqliteTable("banners", {
	id: integer().primaryKey({ autoIncrement: true }),
	title: text().notNull(),
	subtitle: text(),
	imageUrl: text("image_url"), // For background
  active: integer().default(1),
  link: text(),
  buttonText: text("button_text").default("Order Now"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const categories = sqliteTable("categories", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text().notNull(),
	slug: text().notNull(),
	icon: text(), // Optional icon name
  active: integer().default(1),
  order: integer().default(0),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
}, (table) => [
  uniqueIndex("idx_categories_slug").on(table.slug)
]);

export const promos = sqliteTable("promos", {
	id: integer().primaryKey({ autoIncrement: true }),
	title: text().notNull(),
	description: text(),
  badge: text(),
  validUntil: integer("valid_until"),
  active: integer().default(1),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});
