tunnel: 0fdc3a49-28d9-43cf-ad19-7348c6f860cc
credentials-file: C:/Users/HSPC1/.cloudflared/0fdc3a49-28d9-43cf-ad19-7348c6f860cc.json

ingress:
  - hostname: hscopycenter.site
    service: http://127.0.0.1:8081

  - hostname: www.hscopycenter.site
    service: http://127.0.0.1:8081

  - hostname: cetakfoto.hscopycenter.site
    service: http://127.0.0.1:8081

  - hostname: dokumen.hscopycenter.site
    service: http://127.0.0.1:8081

  - hostname: pos.hscopycenter.site
    service: http://127.0.0.1:8080

  - hostname: kasir.hscopycenter.site
    service: http://127.0.0.1:8080

  - hostname: waha.hscopycenter.site
    service: http://127.0.0.1:3000

  - hostname: produk.hscopycenter.site
    service: http://127.0.0.1:80

  - service: http_status:404
